### ISSUE TITLE
Connection with database

### ISSUE THREAD

**Issue by Eduardoespl** [BrightCoders-Institute/reto-reservacion-de-vuelos-ghostbusters#10]
## REQUIREMENTS / DESCRIPTION

> As a React Native developer, I want to establish a connection with Firebase as the database for the project so that I can leverage Firebase's features for data storage, retrieval, and synchronization.

```[tasklist]
### Tasks
- [x] Set up Firebase project
- [x] Install and Initialize Firebase SDK
- [x] Establish connection with Firebase
```
