### ISSUE TITLE
Finish up login and register screens

### ISSUE THREAD

**Issue by Eduardoespl** [BrightCoders-Institute/reto-reservacion-de-vuelos-ghostbusters#11]
## REQUIREMENTS / DESCRIPTION

> As a user of the application, I want the login and register screens to be completed so that I can securely access the app's features and create a new account easily.

## Goal
The primary goal of this issue is to finalize the implementation of the login and register screens in the React Native project. These screens are essential for users to authenticate themselves and access the application's functionalities.

```[tasklist]
### Tasks
- [x] It should include input fields for username/email and password.
- [x] Allow user to see the password by clicking on the eye icon.
- [x] Check box must be checked on click
```

## DESIGN

![image](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-ghostbusters/assets/112664006/a93f3294-604c-4235-8485-b5c6ec3875b7)
