### ISSUE TITLE
Implement the logic for login and register users

### ISSUE THREAD

**Issue by Eduardoespl** [BrightCoders-Institute/reto-reservacion-de-vuelos-ghostbusters#13]
## REQUIREMENTS / DESCRIPTION

> As a developer working on the project, I need to implement the logic to register new users in Firebase so that users can create accounts and then create a method to allow them to login into the app with the existing credentials. 

## Goal
> The main goal of this issue is to integrate Firebase authentication into the project and implement the necessary logic to allow users to register and create new accounts securely, As weel allow them to access an existing account.

```[tasklist]
### Tasks
- [x] Design and implement a user registration form where users can enter their desire name, email, and password.
- [x] Design and implement a login form where users can enter their credentials to log in.
- [x] Implement the logic to capture user input from the forms.
- [x] Use the Firebase Authentication SDK to create a new user account using the provided email and password.
- [x] Use the Firebase Authentication SDK to authenticate the user using the provided credentials.
- [ ] Handle potential errors during the registration or login process (e.g., email already in use) and display appropriate error messages to the user.
```
