### ISSUE TITLE
Retrieve Flight Data from Firebase for Flight Component

### ISSUE THREAD

**Issue by Eduardoespl** [BrightCoders-Institute/reto-reservacion-de-vuelos-ghostbusters#25]
## REQUIREMENTS / DESCRIPTION

> As a user of the application, I want the Flight component to display relevant flight information retrieved from Firebase so that I can view and interact with flight details within the application.

## GOAL
> The main goal of this issue is to implement the functionality to retrieve flight data from Firebase and populate the Flight component with the relevant information.

```[tasklist]
### Tasks
- [x] Firebase Database Setup.
- [x] Define Flight Data Structure.
- [x] Retrieve Flight Data.
- [x] Integrate Flight Component.
```
